# Generated by Django 5.1.15 on 2026-07-07 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_seed_default_currency"),
        ("orders", "0002_phase6_cart_checkout_payments"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "gateway_key",
                    models.CharField(db_index=True, max_length=40, verbose_name="Gateway key"),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Amount"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "external_intent_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=120, verbose_name="External intent ID"
                    ),
                ),
                (
                    "external_transaction_id",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="External transaction ID"
                    ),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="Metadata")),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_transactions",
                        to="core.currency",
                        verbose_name="Currency",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="orders.order",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment transaction",
                "verbose_name_plural": "Payment transactions",
                "indexes": [
                    models.Index(fields=["order", "status"], name="pay_tx_order_status_idx"),
                    models.Index(
                        fields=["gateway_key", "status"], name="pay_tx_gateway_status_idx"
                    ),
                ],
            },
        ),
    ]
