# Generated by Django 5.1.15 on 2026-09-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_razorpaywebhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='attempted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text="When the customer actually engaged the gateway's checkout widget (e.g. clicked Pay Now), as opposed to just having a pending intent created server-side at order placement. Null means the customer never made it this far — used to keep such orders out of the Abandoned Checkout list until there was something to actually abandon.", null=True, verbose_name='Attempted at'),
        ),
    ]
