# Generated by Django 5.1.15 on 2026-07-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_phase2_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliverySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display label, e.g. Morning 9am–12pm.",
                        max_length=80,
                        verbose_name="Name",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Start time")),
                ("end_time", models.TimeField(verbose_name="End time")),
                (
                    "is_midnight",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="When True, only offered when product config allows midnight delivery.",
                        verbose_name="Is midnight slot",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Delivery slot",
                "verbose_name_plural": "Delivery slots",
                "indexes": [
                    models.Index(
                        fields=["is_active", "is_midnight"], name="delivery_slot_active_idx"
                    )
                ],
            },
        ),
    ]
