# Generated by Django 5.1.15 on 2026-07-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_phase7_delivery_order_tracking"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="deliveryslot",
            name="delivery_slot_active_idx",
        ),
        migrations.AlterField(
            model_name="city",
            name="delivery_charge_base",
            field=models.DecimalField(
                decimal_places=2,
                default=25,
                help_text="Default delivery fee for this city in the store currency.",
                max_digits=10,
                verbose_name="Base delivery charge",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="same_day_cutoff_hour",
            field=models.PositiveSmallIntegerField(
                default=14,
                help_text="Local hour (0–23) after which same-day delivery slots are hidden.",
                verbose_name="Same-day cutoff hour",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="Two-letter ISO code, e.g. QA.",
                max_length=2,
                unique=True,
                verbose_name="ISO country code",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when this record was first created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Timestamp when this record was last modified.",
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryslot",
            name="is_midnight",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Deprecated mirror of slot_type=midnight; kept for template stability.",
                verbose_name="Is midnight slot",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryslot",
            name="max_capacity_per_day",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Maximum bookings allowed for this slot on a single date.",
                verbose_name="Max capacity per day",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryslot",
            name="slot_type",
            field=models.CharField(
                choices=[
                    ("morning", "Morning"),
                    ("evening", "Evening"),
                    ("specific", "Specific"),
                    ("midnight", "Midnight"),
                ],
                db_index=True,
                default="morning",
                max_length=20,
                verbose_name="Slot type",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryslotbooking",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when this record was first created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryslotbooking",
            name="current_bookings",
            field=models.PositiveIntegerField(default=0, verbose_name="Current bookings"),
        ),
        migrations.AlterField(
            model_name="deliveryslotbooking",
            name="date",
            field=models.DateField(db_index=True, verbose_name="Delivery date"),
        ),
        migrations.AlterField(
            model_name="deliveryslotbooking",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slot_bookings",
                to="delivery.deliveryslot",
                verbose_name="Delivery slot",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryslotbooking",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Timestamp when this record was last modified.",
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="center_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Center latitude",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="center_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Center longitude",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zones",
                to="delivery.city",
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when this record was first created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="postcodes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of postcode strings served by this zone.",
                verbose_name="Served postcodes",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="radius_km",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Used when postcodes list is empty.",
                max_digits=8,
                null=True,
                verbose_name="Radius (km)",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryzone",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Timestamp when this record was last modified.",
                verbose_name="Updated at",
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryslot",
            index=models.Index(fields=["is_active", "slot_type"], name="delivery_slot_active_idx"),
        ),
    ]
