# Generated by Django 5.1.15 on 2026-07-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_phase9_admin_cms_marketing_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryslot',
            name='is_midnight',
        ),
        migrations.AlterField(
            model_name='deliveryslot',
            name='slot_type',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('specific', 'Specific')], db_index=True, default='morning', max_length=20, verbose_name='Slot type'),
        ),
    ]
