# Generated by Django 5.1.15 on 2026-07-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_checkoutsession_delivery_slot'),
        ('delivery', '0005_remove_deliveryslot_is_midnight_and_more'),
        ('orders', '0005_remove_order_delivery_slot_booking_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deliveryslotbooking',
            name='delivery_slot_date_unique',
        ),
        migrations.RemoveIndex(
            model_name='deliveryslotbooking',
            name='delivery_booking_slot_date_idx',
        ),
        migrations.RemoveField(
            model_name='deliveryslotbooking',
            name='slot',
        ),
        migrations.DeleteModel(
            name='DeliverySlot',
        ),
        migrations.DeleteModel(
            name='DeliverySlotBooking',
        ),
    ]
