# Generated by Django 5.1.15 on 2026-07-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="ISO 4217 currency code, e.g. QAR or USD.",
                        max_length=3,
                        unique=True,
                        verbose_name="Currency code",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Display symbol shown alongside prices, e.g. ر.ق or $.",
                        max_length=8,
                        verbose_name="Symbol",
                    ),
                ),
                (
                    "exchange_rate_to_base",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Multiplier to convert this currency into the platform base currency.",
                        max_digits=18,
                        verbose_name="Exchange rate to base",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="When True, this currency is the storefront default.",
                        verbose_name="Is default",
                    ),
                ),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "indexes": [
                    models.Index(fields=["is_default"], name="core_currency_is_default_idx")
                ],
            },
        ),
    ]
