# Generated by Django 5.1.15 on 2026-07-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_seed_default_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("site_name", models.CharField(default="Floward", max_length=120)),
                ("logo_url", models.URLField(blank=True, verbose_name="Logo URL")),
                ("primary_color", models.CharField(default="#1B4332", max_length=7)),
                ("secondary_color", models.CharField(default="#D4A574", max_length=7)),
                ("font_family", models.CharField(default="Inter, sans-serif", max_length=120)),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                ("default_language", models.CharField(default="en", max_length=5)),
                (
                    "tax_rate_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "default_shipping_charge",
                    models.DecimalField(decimal_places=2, default=25, max_digits=10),
                ),
                (
                    "card_gateway_public_key_env",
                    models.CharField(
                        default="CARD_GATEWAY_PUBLIC_KEY",
                        help_text="Environment variable name for the card gateway public key.",
                        max_length=80,
                    ),
                ),
                (
                    "qatar_gateway_public_key_env",
                    models.CharField(blank=True, default="QATAR_GATEWAY_PUBLIC_KEY", max_length=80),
                ),
                (
                    "order_email_template_slug",
                    models.CharField(default="order-status", max_length=80),
                ),
                (
                    "whatsapp_template_slug",
                    models.CharField(default="order-whatsapp", max_length=80),
                ),
                (
                    "default_currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
    ]
