# Generated by Django 5.1.15 on 2026-07-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_phase9_admin_cms_marketing_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='When False, this currency is hidden/inactive on the storefront.', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_shipping_charge',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='DESERT STAR MOBILE PHONES', max_length=120),
        ),
    ]
