# Generated by Django 5.1.15 on 2026-07-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_seed_inr_deactivate_qar_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='razorpay_key_id',
            field=models.CharField(blank=True, help_text='Razorpay Key ID / Test Key ID for payment processing.', max_length=120, verbose_name='Razorpay Key ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='razorpay_key_secret',
            field=models.CharField(blank=True, help_text='Razorpay Key Secret / Test Key Secret for payment signature verification.', max_length=120, verbose_name='Razorpay Key Secret'),
        ),
    ]
