# Generated by Django 5.1.15 on 2026-07-21 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_wholesale_rate'),
        ('core', '0007_sitesettings_razorpay_key_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was first created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('message', models.TextField(verbose_name='Message')),
                ('product', models.ForeignKey(blank=True, help_text='The product this inquiry is about (for quote requests).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='catalog.product', verbose_name='Related Product')),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
            },
        ),
    ]
