# Generated by Django 5.1.15 on 2026-07-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='vendor_email',
            field=models.EmailField(blank=True, help_text='Email address to receive quote requests and contact inquiries.', max_length=254, verbose_name='Vendor Email'),
        ),
    ]
