# Generated by Django 5.1.15 on 2026-07-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_vendor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo'),
        ),
    ]
