# Generated by Django 5.1.15 on 2026-07-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_darken_desert_tech_accent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinquiry',
            name='product',
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#0369A1', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#0B1220', max_length=7),
        ),
    ]
