# Generated by Django 5.1.15 on 2026-09-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_update_zaye_lennox_contact_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="shiprocket_email",
            field=models.EmailField(
                blank=True,
                help_text="Shiprocket account email used to authenticate with the Shiprocket API.",
                max_length=254,
                verbose_name="Shiprocket Email",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shiprocket_password",
            field=models.CharField(
                blank=True,
                help_text="Shiprocket account password used to authenticate with the Shiprocket API.",
                max_length=120,
                verbose_name="Shiprocket Password",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shiprocket_pickup_location",
            field=models.CharField(
                blank=True,
                help_text="Pickup location nickname configured in your Shiprocket account (e.g. Primary).",
                max_length=120,
                verbose_name="Shiprocket Pickup Location",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shiprocket_pickup_pincode",
            field=models.CharField(
                blank=True,
                help_text="Pincode used for serviceability/rate checks at checkout.",
                max_length=10,
                verbose_name="Shiprocket Pickup Pincode",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="shiprocket_webhook_token",
            field=models.CharField(
                blank=True,
                help_text="Secret token Shiprocket sends back on status webhooks (X-Api-Key header or token query param) — must match what you configure in the Shiprocket dashboard.",
                max_length=255,
                verbose_name="Shiprocket Webhook Token",
            ),
        ),
    ]
