# Generated by Django 5.1.15 on 2026-09-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_sitesettings_payu_gateway"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="gstin",
            field=models.CharField(
                blank=True,
                help_text="Your GST registration number, shown on customer invoices.",
                max_length=15,
                verbose_name="GSTIN",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="pan_number",
            field=models.CharField(blank=True, max_length=10, verbose_name="PAN"),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="registered_state",
            field=models.CharField(
                blank=True,
                help_text="Your GST-registered state. Compared to each order's delivery state to decide CGST+SGST (same state) vs IGST (different state).",
                max_length=120,
                verbose_name="Registered State",
            ),
        ),
    ]
