# Generated by Django 5.1.15 on 2026-09-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_sitesettings_gstin_sitesettings_pan_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="shop_address",
            field=models.TextField(
                blank=True,
                help_text="Full postal address shown on the storefront and on customer invoices/bills. "
                "Falls back to the server's STORE_ADDRESS setting when left blank.",
                verbose_name="Shop Address",
            ),
        ),
    ]
