# Generated by Django 5.1.15 on 2026-09-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_sitesettings_shop_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="use_shiprocket_delivery_charge",
            field=models.BooleanField(
                default=True,
                help_text="When on, checkout charges customers Shiprocket's live-quoted courier rate "
                "for their delivery pincode. When off, every order is charged the flat 'Default "
                "shipping charge' below instead. Either way, orders are still created and shipped "
                "through Shiprocket exactly the same — this only controls what the customer pays "
                "for delivery.",
                verbose_name="Charge customers Shiprocket's live rate",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="default_shipping_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=50,
                help_text="Flat delivery charge applied to every order when the Shiprocket live rate "
                "above is switched off.",
                max_digits=10,
                verbose_name="Default shipping charge",
            ),
        ),
    ]
