# Generated by Django 5.1.15 on 2026-09-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_sitesettings_use_shiprocket_delivery_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="show_shop_address_on_invoice",
            field=models.BooleanField(
                default=True,
                help_text="Print the shop address above in the header of customer bills/invoices. Turn off to leave it off the bill entirely.",
                verbose_name="Show shop address on bills",
            ),
        ),
    ]
