# Generated by Django 5.1.15 on 2026-09-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_sitesettings_show_shop_address_on_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="charge_for_delivery",
            field=models.BooleanField(
                default=True,
                help_text="Turn off to give every customer free delivery: no delivery charge is added to the cart, checkout, order total, payment or bill, and checkout says 'Free delivery'. Shiprocket still checks the pincode, shows the estimated delivery date and ships the order exactly as before - it just never affects what the customer pays.",
                verbose_name="Charge customers for delivery",
            ),
        ),
    ]
