# Generated by Django 5.1.15 on 2026-07-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomepageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero_slider", "Hero Slider"),
                            ("shop_by_occasion", "Shop by Occasion"),
                            ("shop_by_category", "Shop by Category"),
                            ("premium_collection", "Premium Collection"),
                            ("seasonal_collection", "Seasonal Collection"),
                            ("luxury_collection", "Luxury Collection"),
                            ("same_day_delivery", "Same Day Delivery"),
                            ("trending", "Trending"),
                            ("best_sellers", "Best Sellers"),
                            ("featured_brands", "Featured Brands"),
                            ("corporate_gifts_banner", "Corporate Gifts Banner"),
                            ("subscription_banner", "Subscription Banner"),
                            ("reviews", "Reviews"),
                            ("instagram_gallery", "Instagram Gallery"),
                            ("newsletter", "Newsletter"),
                        ],
                        db_index=True,
                        help_text="Determines which template partial renders this block.",
                        max_length=40,
                        verbose_name="Section type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional heading shown above the section.",
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True,
                        default=0,
                        help_text="Lower values appear higher on the homepage.",
                        verbose_name="Display order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive sections are excluded from the cached homepage snapshot.",
                        verbose_name="Is active",
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Section-specific settings JSON, e.g. {"occasion_ids": [1,2], "slides": [...], "product_ids": [3,4]}',
                        verbose_name="Configuration",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homepage section",
                "verbose_name_plural": "Homepage sections",
                "ordering": ["display_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="cms_hp_section_active_ord_idx"
                    )
                ],
            },
        ),
    ]
