# Generated by Django 5.1.15 on 2026-07-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_phase4_homepage_sections"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(db_index=True, default=False, verbose_name="Is published"),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Leave blank to publish immediately when is_published is checked.",
                        null=True,
                        verbose_name="Publish at",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image_url", models.URLField(verbose_name="Image URL")),
                ("link_url", models.URLField(blank=True, verbose_name="Link URL")),
                ("display_order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="HTML <title> tag content (max ~70 characters).",
                        max_length=70,
                        verbose_name="Meta title",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="HTML meta description for search engines (max ~160 characters).",
                        max_length=160,
                        verbose_name="Meta description",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image used when this content is shared on social media.",
                        null=True,
                        upload_to="seo/og/",
                        verbose_name="Open Graph image",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(db_index=True, default=False, verbose_name="Is published"),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Leave blank to publish immediately when is_published is checked.",
                        null=True,
                        verbose_name="Publish at",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier used in public-facing paths.",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                ("body", models.TextField()),
                ("excerpt", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Blog post",
                "verbose_name_plural": "Blog posts",
                "ordering": ["-publish_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(db_index=True, default=False, verbose_name="Is published"),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Leave blank to publish immediately when is_published is checked.",
                        null=True,
                        verbose_name="Publish at",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
                ("display_order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "verbose_name": "FAQ item",
                "verbose_name_plural": "FAQ items",
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="HTML <title> tag content (max ~70 characters).",
                        max_length=70,
                        verbose_name="Meta title",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="HTML meta description for search engines (max ~160 characters).",
                        max_length=160,
                        verbose_name="Meta description",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image used when this content is shared on social media.",
                        null=True,
                        upload_to="seo/og/",
                        verbose_name="Open Graph image",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(db_index=True, default=False, verbose_name="Is published"),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Leave blank to publish immediately when is_published is checked.",
                        null=True,
                        verbose_name="Publish at",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier used in public-facing paths.",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                ("body", models.TextField()),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="PolicyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="HTML <title> tag content (max ~70 characters).",
                        max_length=70,
                        verbose_name="Meta title",
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="HTML meta description for search engines (max ~160 characters).",
                        max_length=160,
                        verbose_name="Meta description",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image used when this content is shared on social media.",
                        null=True,
                        upload_to="seo/og/",
                        verbose_name="Open Graph image",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(db_index=True, default=False, verbose_name="Is published"),
                ),
                (
                    "publish_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Leave blank to publish immediately when is_published is checked.",
                        null=True,
                        verbose_name="Publish at",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier used in public-facing paths.",
                        max_length=255,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                ("body", models.TextField()),
                ("policy_type", models.CharField(db_index=True, default="general", max_length=40)),
            ],
            options={
                "verbose_name": "Policy document",
                "verbose_name_plural": "Policy documents",
                "ordering": ["title"],
            },
        ),
        migrations.AlterField(
            model_name="homepagesection",
            name="config",
            field=models.JSONField(blank=True, default=dict, verbose_name="Configuration"),
        ),
        migrations.AlterField(
            model_name="homepagesection",
            name="display_order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, verbose_name="Display order"
            ),
        ),
        migrations.AlterField(
            model_name="homepagesection",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
        ),
        migrations.AlterField(
            model_name="homepagesection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("hero_slider", "Hero Slider"),
                    ("shop_by_occasion", "Shop by Occasion"),
                    ("shop_by_category", "Shop by Category"),
                    ("premium_collection", "Premium Collection"),
                    ("seasonal_collection", "Seasonal Collection"),
                    ("luxury_collection", "Luxury Collection"),
                    ("same_day_delivery", "Same Day Delivery"),
                    ("trending", "Trending"),
                    ("best_sellers", "Best Sellers"),
                    ("featured_brands", "Featured Brands"),
                    ("corporate_gifts_banner", "Corporate Gifts Banner"),
                    ("subscription_banner", "Subscription Banner"),
                    ("reviews", "Reviews"),
                    ("instagram_gallery", "Instagram Gallery"),
                    ("newsletter", "Newsletter"),
                ],
                db_index=True,
                max_length=40,
                verbose_name="Section type",
            ),
        ),
        migrations.AlterField(
            model_name="homepagesection",
            name="title",
            field=models.CharField(blank=True, max_length=200, verbose_name="Title"),
        ),
    ]
