# Generated by Django 5.1.15 on 2026-07-08 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_phase9_admin_cms_marketing_reports"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Used as the media alt text for accessibility and SEO.",
                        max_length=200,
                        verbose_name="Title",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Photo slide. Ignored when a video is uploaded.",
                        upload_to="cms/hero/images/",
                        verbose_name="Photo",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Video slide (mp4/webm). Takes priority over the photo.",
                        upload_to="cms/hero/videos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["mp4", "webm", "ogg", "mov"]
                            )
                        ],
                        verbose_name="Video",
                    ),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        help_text="Still image shown while the video loads.",
                        upload_to="cms/hero/posters/",
                        verbose_name="Video poster",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        db_index=True, default=0, verbose_name="Display order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Hero slide",
                "verbose_name_plural": "Hero slides",
                "ordering": ["display_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "display_order"], name="cms_hero_active_order_idx"
                    )
                ],
            },
        ),
    ]
