# Generated by Django 5.1.15 on 2026-07-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_heroslide"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Banner",
        ),
    ]
