# Generated by Django 5.1.15 on 2026-07-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_delete_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagesection",
            name="section_type",
            field=models.CharField(
                choices=[
                    ("hero_slider", "Hero Slider"),
                    ("shop_by_occasion", "Shop by Occasion"),
                    ("shop_by_recipient", "Shop by Recipient"),
                    ("shop_by_category", "Shop by Category"),
                    ("premium_collection", "Premium Collection"),
                    ("seasonal_collection", "Seasonal Collection"),
                    ("luxury_collection", "Luxury Collection"),
                    ("same_day_delivery", "Same Day Delivery"),
                    ("trending", "Trending"),
                    ("best_sellers", "Best Sellers"),
                    ("featured_brands", "Featured Brands"),
                    ("corporate_gifts_banner", "Corporate Gifts Banner"),
                    ("subscription_banner", "Subscription Banner"),
                    ("marketing_features", "Marketing Feature Cards"),
                    ("reviews", "Reviews"),
                    ("instagram_gallery", "Instagram Gallery"),
                    ("newsletter", "Newsletter"),
                ],
                db_index=True,
                max_length=40,
                verbose_name="Section type",
            ),
        ),
    ]
