# Generated by Django 5.1.15 on 2026-07-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_homepagesection_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('hero_slider', 'Hero Slider'), ('shop_by_category', 'Shop by Category'), ('premium_collection', 'Premium Collection'), ('seasonal_collection', 'Seasonal Collection'), ('luxury_collection', 'Luxury Collection'), ('featured_products', 'Featured Products'), ('trending', 'Trending'), ('best_sellers', 'Best Sellers'), ('featured_brands', 'Featured Brands'), ('subscription_banner', 'Subscription Banner'), ('marketing_features', 'Marketing Feature Cards'), ('reviews', 'Reviews'), ('instagram_gallery', 'Instagram Gallery'), ('newsletter', 'Newsletter')], db_index=True, max_length=40, verbose_name='Section type'),
        ),
    ]
