# Generated by Django 5.1.15 on 2026-07-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0008_alter_homepagesection_section_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroslide",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Shown over the banner when set. Also used as media alt text.",
                max_length=200,
                verbose_name="Title",
            ),
        ),
    ]
