# Generated by Django 5.1.15 on 2026-07-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_alter_heroslide_title_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo slide. Ignored when a video is uploaded. Note: All banners should have the same resolution.', upload_to='cms/hero/images/', verbose_name='Photo'),
        ),
    ]
