# Generated by Django 5.2.17 on 2026-08-05 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_alter_heroslide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('hero_slider', 'Hero Slider'), ('secondary_banner', 'Secondary Banner'), ('shop_by_category', 'Shop by Category'), ('featured_products', 'Featured Products'), ('new_arrivals', 'New Arrivals'), ('best_sellers', 'Best Sellers'), ('featured_brands', 'Featured Brands'), ('subscription_banner', 'Subscription Banner'), ('marketing_features', 'Marketing Feature Cards'), ('reviews', 'Reviews'), ('instagram_gallery', 'Instagram Gallery'), ('newsletter', 'Newsletter')], db_index=True, max_length=40, verbose_name='Section type'),
        ),
        migrations.CreateModel(
            name='SecondarySlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was first created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated at')),
                ('title', models.CharField(blank=True, help_text='Shown over the banner when set. Also used as media alt text.', max_length=200, verbose_name='Title')),
                ('image', models.ImageField(blank=True, help_text='Photo slide. Ignored when a video is uploaded. Note: All banners should have the same resolution (9:3 ratio).', upload_to='cms/secondary/images/', verbose_name='Photo')),
                ('video', models.FileField(blank=True, help_text='Video slide (mp4/webm). Takes priority over the photo.', upload_to='cms/secondary/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'ogg', 'mov'])], verbose_name='Video')),
                ('poster', models.ImageField(blank=True, help_text='Still image shown while the video loads.', upload_to='cms/secondary/posters/', verbose_name='Video poster')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Display order')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Secondary slide',
                'verbose_name_plural': 'Secondary slides',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='cms_secondary_active_ord_idx')],
            },
        ),
    ]
