# Generated by Django 5.2.17 on 2026-09-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_secondaryslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesection',
            name='section_type',
            field=models.CharField(choices=[('hero_slider', 'Hero Slider'), ('secondary_banner', 'Secondary Banner'), ('shop_by_category', 'Shop by Category'), ('featured_products', 'Featured Products'), ('new_arrivals', 'New Arrivals'), ('best_sellers', 'Best Sellers'), ('featured_brands', 'Featured Brands'), ('subscription_banner', 'Subscription Banner'), ('marketing_features', 'Marketing Feature Cards'), ('reviews', 'Reviews'), ('instagram_gallery', 'Instagram Gallery'), ('newsletter', 'Newsletter'), ('combos', 'Combos')], db_index=True, max_length=40, verbose_name='Section type'),
        ),
    ]
