# Generated by Django 5.1.15 on 2026-07-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_phase9_admin_cms_marketing_reports"),
        ("cart", "0001_phase6_cart_checkout_payments"),
        ("catalog", "0001_phase3_product_catalog"),
        ("marketing", "0001_phase6_cart_checkout_payments"),
        ("orders", "0003_phase7_delivery_order_tracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbandonedCartRecovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("notified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_logs",
                        to="cart.cart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abandoned cart recovery",
                "verbose_name_plural": "Abandoned cart recoveries",
            },
        ),
        migrations.CreateModel(
            name="CouponRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon redemption",
                "verbose_name_plural": "Coupon redemptions",
            },
        ),
        migrations.CreateModel(
            name="FlashSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("discount_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("starts_at", models.DateTimeField(db_index=True)),
                ("ends_at", models.DateTimeField(db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "products",
                    models.ManyToManyField(related_name="flash_sales", to="catalog.product"),
                ),
            ],
            options={
                "verbose_name": "Flash sale",
                "verbose_name_plural": "Flash sales",
            },
        ),
        migrations.RenameModel(
            old_name="GiftVoucher",
            new_name="GiftCard",
        ),
        migrations.AddField(
            model_name="giftcard",
            name="initial_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254, unique=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Newsletter subscriber",
                "verbose_name_plural": "Newsletter subscribers",
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("referred_email", models.EmailField(db_index=True, max_length=254)),
                ("code", models.CharField(db_index=True, max_length=40, unique=True)),
                ("is_converted", models.BooleanField(db_index=True, default=False)),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to="accounts.customerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Referral",
                "verbose_name_plural": "Referrals",
            },
        ),
        migrations.AddField(
            model_name="coupon",
            name="applicable_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="coupons",
                to="catalog.category",
                verbose_name="Applicable categories",
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="max_uses",
            field=models.PositiveIntegerField(
                blank=True, help_text="Blank = unlimited.", null=True, verbose_name="Max total uses"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="max_uses_per_customer",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Max uses per customer"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="min_order_value",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Minimum order value"
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="valid_from",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="coupon",
            name="valid_until",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_type",
            field=models.CharField(
                choices=[("percent", "Percentage"), ("fixed", "Fixed amount")],
                default="percent",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="discount_value",
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Value"),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="couponredemption",
            name="coupon",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="redemptions",
                to="marketing.coupon",
            ),
        ),
        migrations.AddField(
            model_name="couponredemption",
            name="customer_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupon_redemptions",
                to="accounts.customerprofile",
            ),
        ),
        migrations.AddField(
            model_name="couponredemption",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coupon_redemptions",
                to="orders.order",
            ),
        ),
        migrations.AddIndex(
            model_name="abandonedcartrecovery",
            index=models.Index(fields=["cart"], name="mkt_abandoned_cart_idx"),
        ),
        migrations.AddIndex(
            model_name="couponredemption",
            index=models.Index(
                fields=["coupon", "customer_profile"], name="mkt_coupon_redemption_idx"
            ),
        ),
    ]
