# Generated by Django 5.1.15 on 2026-07-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_phase9_admin_cms_marketing_reports"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="giftcard",
            options={"verbose_name": "Gift card", "verbose_name_plural": "Gift cards"},
        ),
        migrations.AlterField(
            model_name="giftcard",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Current balance"
            ),
        ),
        migrations.AlterField(
            model_name="giftcard",
            name="code",
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name="giftcard",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
