# Generated by Django 5.1.15 on 2026-07-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0003_alter_giftcard_options_alter_giftcard_balance_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GiftCard",
        ),
    ]
