# Generated by Django 5.1.15 on 2026-07-07 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_seed_default_currency"),
        ("delivery", "0001_phase2_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Short label, e.g. Home or Office.",
                        max_length=50,
                        verbose_name="Label",
                    ),
                ),
                (
                    "line1",
                    models.CharField(
                        help_text="Street address or building name.",
                        max_length=255,
                        verbose_name="Address line 1",
                    ),
                ),
                (
                    "line2",
                    models.CharField(
                        blank=True,
                        help_text="Apartment, floor, or additional directions.",
                        max_length=255,
                        verbose_name="Address line 2",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="When True, this is the customer's primary delivery address.",
                        verbose_name="Is default",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        help_text="Deliverable city for this address.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="addresses",
                        to="delivery.city",
                        verbose_name="City",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Customer mobile number used for OTP login.",
                        max_length=20,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "phone_verified",
                    models.BooleanField(
                        default=False,
                        help_text="True after a successful OTP verification for this phone.",
                        verbose_name="Phone verified",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("en", "English"), ("ar", "Arabic")],
                        default="en",
                        help_text="Customer's preferred storefront language.",
                        max_length=5,
                        verbose_name="Preferred language",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        help_text="Optional date of birth for personalization.",
                        null=True,
                        verbose_name="Date of birth",
                    ),
                ),
                (
                    "default_address",
                    models.ForeignKey(
                        blank=True,
                        help_text="Customer's primary delivery address.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.address",
                        verbose_name="Default address",
                    ),
                ),
                (
                    "preferred_currency",
                    models.ForeignKey(
                        help_text="Currency used to display prices for this customer.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_profiles",
                        to="core.currency",
                        verbose_name="Preferred currency",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Linked Django auth user.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer profile",
                "verbose_name_plural": "Customer profiles",
            },
        ),
        migrations.AddField(
            model_name="address",
            name="customer_profile",
            field=models.ForeignKey(
                help_text="Owner of this address.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to="accounts.customerprofile",
                verbose_name="Customer profile",
            ),
        ),
        migrations.CreateModel(
            name="OTPRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        help_text="Phone number the OTP was sent to.",
                        max_length=20,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "otp_hash",
                    models.CharField(
                        help_text="Hashed OTP value — plaintext is never stored.",
                        max_length=128,
                        verbose_name="OTP hash",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("signup", "Sign Up"),
                            ("password_reset", "Password Reset"),
                        ],
                        db_index=True,
                        help_text="Reason this OTP was issued.",
                        max_length=20,
                        verbose_name="Purpose",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Timestamp after which this OTP is invalid.",
                        verbose_name="Expires at",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True once the OTP has been successfully verified.",
                        verbose_name="Is used",
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of failed verification attempts.",
                        verbose_name="Attempt count",
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP request",
                "verbose_name_plural": "OTP requests",
                "indexes": [
                    models.Index(
                        fields=["phone", "purpose", "is_used"],
                        name="accounts_otp_phone_purpose_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "gateway_token",
                    models.CharField(
                        help_text="Opaque token returned by the payment gateway.",
                        max_length=255,
                        verbose_name="Gateway token",
                    ),
                ),
                (
                    "card_brand",
                    models.CharField(
                        help_text="Card network, e.g. Visa or Mastercard.",
                        max_length=30,
                        verbose_name="Card brand",
                    ),
                ),
                (
                    "last4",
                    models.CharField(
                        help_text="Last four digits of the card number for display.",
                        max_length=4,
                        verbose_name="Last four digits",
                    ),
                ),
                (
                    "expiry_month",
                    models.PositiveSmallIntegerField(
                        help_text="Card expiry month (1–12).", verbose_name="Expiry month"
                    ),
                ),
                (
                    "expiry_year",
                    models.PositiveSmallIntegerField(
                        help_text="Card expiry four-digit year.", verbose_name="Expiry year"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="When True, this card is pre-selected at checkout.",
                        verbose_name="Is default",
                    ),
                ),
                (
                    "customer_profile",
                    models.ForeignKey(
                        help_text="Owner of this saved payment method.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_payment_methods",
                        to="accounts.customerprofile",
                        verbose_name="Customer profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved payment method",
                "verbose_name_plural": "Saved payment methods",
            },
        ),
        migrations.CreateModel(
            name="CorporateAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        help_text="Registered legal or trading name.",
                        max_length=200,
                        verbose_name="Company name",
                    ),
                ),
                (
                    "trade_license_number",
                    models.CharField(
                        db_index=True,
                        help_text="Government-issued trade license identifier.",
                        max_length=100,
                        unique=True,
                        verbose_name="Trade license number",
                    ),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current admin review state.",
                        max_length=20,
                        verbose_name="Approval status",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin user who approved or rejected this account.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_corporate_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approved by",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Corporate account manager login.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corporate_account",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Corporate account",
                "verbose_name_plural": "Corporate accounts",
                "indexes": [
                    models.Index(fields=["approval_status"], name="acct_corp_approval_idx")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(fields=["phone"], name="accounts_profile_phone_idx"),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["customer_profile", "is_default"], name="accounts_address_default_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("customer_profile",),
                name="accounts_one_default_address_per_customer",
            ),
        ),
        migrations.AddConstraint(
            model_name="savedpaymentmethod",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("customer_profile",),
                name="accounts_one_default_payment_per_customer",
            ),
        ),
    ]
