# Generated by Django 5.1.15 on 2026-07-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_phase8_subscriptions_wishlist_gift_calendar"),
        ("catalog", "0001_phase3_product_catalog"),
        ("recurring", "0002_phase9_admin_cms_marketing_reports"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftreminder",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when this record was first created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="giftreminder",
            name="customer_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gift_reminders",
                to="accounts.customerprofile",
                verbose_name="Customer profile",
            ),
        ),
        migrations.AlterField(
            model_name="giftreminder",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="giftreminder",
            name="last_notified_on",
            field=models.DateField(blank=True, null=True, verbose_name="Last notified on"),
        ),
        migrations.AlterField(
            model_name="giftreminder",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="giftreminder",
            name="notify_days_before",
            field=models.PositiveSmallIntegerField(default=7, verbose_name="Notify days before"),
        ),
        migrations.AlterField(
            model_name="giftreminder",
            name="occasion_type",
            field=models.CharField(
                choices=[
                    ("birthday", "Birthday"),
                    ("anniversary", "Anniversary"),
                    ("valentine", "Valentine's Day"),
                    ("mothers_day", "Mother's Day"),
                    ("fathers_day", "Father's Day"),
                    ("ramadan", "Ramadan"),
                    ("eid", "Eid"),
                    ("custom", "Custom"),
                ],
                max_length=20,
                verbose_name="Occasion type",
            ),
        ),
        migrations.AlterField(
            model_name="giftreminder",
            name="recipient_name",
            field=models.CharField(max_length=120, verbose_name="Recipient name"),
        ),
        migrations.AlterField(
            model_name="giftreminder",
            name="reminder_date",
            field=models.DateField(db_index=True, verbose_name="Reminder date"),
        ),
        migrations.AlterField(
            model_name="giftreminder",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Timestamp when this record was last modified.",
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when this record was first created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="customer_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="accounts.customerprofile",
                verbose_name="Customer profile",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="delivery_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="accounts.address",
                verbose_name="Delivery address",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="recurring_schedule",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscription",
                to="recurring.recurringschedule",
                verbose_name="Recurring schedule",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("paused", "Paused"), ("cancelled", "Cancelled")],
                db_index=True,
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Timestamp when this record was last modified.",
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when this record was first created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="customer_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlists",
                to="accounts.customerprofile",
                verbose_name="Customer profile",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="session_key",
            field=models.CharField(
                blank=True, db_index=True, max_length=40, null=True, verbose_name="Session key"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="share_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Signed token for read-only shared access.",
                max_length=255,
                verbose_name="Share token",
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Timestamp when this record was last modified.",
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="wishlistitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when this record was first created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="wishlistitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="wishlistitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist_items",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="wishlistitem",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Timestamp when this record was last modified.",
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="wishlistitem",
            name="wishlist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="accounts.wishlist",
                verbose_name="Wishlist",
            ),
        ),
    ]
