# Generated by Django 5.1.15 on 2026-07-15 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_phase9_admin_cms_marketing_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English')], default='en', help_text="Customer's preferred storefront language.", max_length=5, verbose_name='Preferred language'),
        ),
        migrations.CreateModel(
            name='EmailOTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was first created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated at')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email address')),
                ('otp_hash', models.CharField(max_length=128, verbose_name='OTP hash')),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('signup', 'Sign Up'), ('password_reset', 'Password Reset')], db_index=True, max_length=20, verbose_name='Purpose')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='Expires at')),
                ('is_used', models.BooleanField(db_index=True, default=False, verbose_name='Is used')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, verbose_name='Attempt count')),
            ],
            options={
                'verbose_name': 'Email OTP request',
                'verbose_name_plural': 'Email OTP requests',
                'indexes': [models.Index(fields=['email', 'purpose', 'is_used'], name='acct_email_otp_idx')],
            },
        ),
        migrations.CreateModel(
            name='Wholesaler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was first created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated at')),
                ('company_name', models.CharField(help_text='Registered legal or trading name of the wholesaler.', max_length=200, verbose_name='Company name')),
                ('phone_number', models.CharField(blank=True, default='', help_text='Contact phone number of the wholesaler.', max_length=20, verbose_name='Phone number')),
                ('place', models.CharField(blank=True, default='', help_text='Location or city of the wholesaler.', max_length=255, verbose_name='Place')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20, verbose_name='Approval status')),
                ('referrer_page', models.CharField(blank=True, help_text='The page URL the user came from during registration.', max_length=500, verbose_name='Referrer page')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_wholesalers', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('user', models.OneToOneField(help_text='Wholesaler manager login.', on_delete=django.db.models.deletion.CASCADE, related_name='wholesaler_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wholesaler',
                'verbose_name_plural': 'Wholesalers',
                'indexes': [models.Index(fields=['approval_status'], name='wholesaler_approval_idx')],
            },
        ),
    ]
