# Generated by Django 5.1.15 on 2026-07-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customerprofile_preferred_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholesaler',
            name='place',
        ),
        migrations.AddField(
            model_name='wholesaler',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Address of the wholesaler.', max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='wholesaler',
            name='gst',
            field=models.CharField(blank=True, default='', help_text='GST number of the wholesaler.', max_length=50, verbose_name='GST'),
        ),
    ]
