# Generated by Django 5.1.15 on 2026-07-17 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_wholesaler_place_wholesaler_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftreminder',
            name='customer_profile',
        ),
        migrations.DeleteModel(
            name='CorporateAccount',
        ),
        migrations.DeleteModel(
            name='GiftReminder',
        ),
    ]
