# Generated by Django 5.1.15 on 2026-08-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_wholesaler'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.CharField(blank=True, db_index=True, help_text='Delivery pincode/postal code — required for courier serviceability (e.g. Shiprocket).', max_length=10, verbose_name='Pincode'),
        ),
    ]
