# Generated by Django 5.1.15 on 2026-08-04 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_address_pincode'),
        ('delivery', '0006_remove_deliveryslotbooking_slot_delete_deliveryslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city_name',
            field=models.CharField(blank=True, help_text='Free-text city entered at checkout (pincode-based flow).', max_length=120, verbose_name='City / Town'),
        ),
        migrations.AddField(
            model_name='address',
            name='state_name',
            field=models.CharField(blank=True, help_text='Free-text state entered at checkout — required by Shiprocket for courier booking.', max_length=120, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Legacy same-day delivery zone city. Optional — new (pincode-based) addresses leave this blank.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='delivery.city', verbose_name='City'),
        ),
    ]
