# Generated by Django 5.1.15 on 2026-09-16 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_address_city_name_address_state_name_and_more"),
        ("delivery", "0006_remove_deliveryslotbooking_slot_delete_deliveryslot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="company_name",
            field=models.CharField(
                blank=True,
                help_text="Registered business name to print on the GST invoice's Bill To section.",
                max_length=150,
                verbose_name="Company name",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="gstin",
            field=models.CharField(
                blank=True,
                help_text="Customer's 15-character GST identification number, shown on the invoice when set.",
                max_length=15,
                verbose_name="GSTIN",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="is_billing",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="When True, this is the customer's primary billing address for GST invoicing.",
                verbose_name="Is billing address",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="default_billing_address",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer's primary billing address, used for GST invoicing at checkout.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="accounts.address",
                verbose_name="Default billing address",
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=["customer_profile", "is_billing"], name="accounts_address_billing_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_billing", True)),
                fields=("customer_profile",),
                name="accounts_one_billing_address_per_customer",
            ),
        ),
    ]
