# Generated by Django 5.1.15 on 2026-07-07 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_phase2_initial"),
        ("cart", "0001_phase6_cart_checkout_payments"),
        ("delivery", "0002_phase5_gift_customization"),
        ("orders", "0001_phase2_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Guest session key when customer_profile is null.",
                        max_length=40,
                        verbose_name="Session key",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(blank=True, null=True, verbose_name="Delivery date"),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="Idempotency key",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("completed", "Completed")],
                        db_index=True,
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("invoice_details", models.JSONField(default=dict, verbose_name="Invoice details")),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkout_sessions",
                        to="accounts.address",
                        verbose_name="Delivery address",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_sessions",
                        to="cart.cart",
                        verbose_name="Cart",
                    ),
                ),
                (
                    "customer_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkout_sessions",
                        to="accounts.customerprofile",
                        verbose_name="Customer profile",
                    ),
                ),
                (
                    "delivery_slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkout_sessions",
                        to="delivery.deliveryslot",
                        verbose_name="Delivery slot",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkout_sessions",
                        to="orders.order",
                        verbose_name="Placed order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checkout session",
                "verbose_name_plural": "Checkout sessions",
                "indexes": [
                    models.Index(fields=["status", "session_key"], name="chk_session_status_idx"),
                    models.Index(fields=["idempotency_key"], name="chk_idempotency_key_idx"),
                ],
            },
        ),
    ]
