# Generated by Django 5.1.15 on 2026-07-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_phase6_cart_checkout_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutsession',
            name='delivery_slot',
        ),
    ]
