# Generated by Django 5.1.15 on 2026-07-07 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_phase3_product_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCustomerReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("report_date", models.DateField(db_index=True, unique=True)),
                ("new_customers", models.PositiveIntegerField(default=0)),
                ("returning_customers", models.PositiveIntegerField(default=0)),
                ("total_active_customers", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Daily customer report",
                "verbose_name_plural": "Daily customer reports",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="DailySalesReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("report_date", models.DateField(db_index=True, unique=True)),
                ("order_count", models.PositiveIntegerField(default=0)),
                ("revenue", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "average_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "coupon_discount_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
            options={
                "verbose_name": "Daily sales report",
                "verbose_name_plural": "Daily sales reports",
                "ordering": ["-report_date"],
            },
        ),
        migrations.CreateModel(
            name="DailyProductPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("report_date", models.DateField(db_index=True)),
                ("units_sold", models.PositiveIntegerField(default=0)),
                ("revenue", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_performance_reports",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily product performance",
                "verbose_name_plural": "Daily product performance",
                "ordering": ["-report_date", "-revenue"],
                "unique_together": {("report_date", "product")},
            },
        ),
        migrations.CreateModel(
            name="InventorySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("report_date", models.DateField(db_index=True)),
                ("stock_quantity", models.PositiveIntegerField()),
                ("low_stock_threshold", models.PositiveIntegerField()),
                ("is_low_stock", models.BooleanField(db_index=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_snapshots",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory snapshot",
                "verbose_name_plural": "Inventory snapshots",
                "ordering": ["-report_date"],
                "unique_together": {("report_date", "product")},
            },
        ),
    ]
