# Generated by Django 5.1.15 on 2026-07-07 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recurring", "0001_phase8_recurring_engine"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="recurringschedule",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when this record was first created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="recurringschedule",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_schedules_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="recurringschedule",
            name="frequency",
            field=models.CharField(
                choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                max_length=20,
                verbose_name="Frequency",
            ),
        ),
        migrations.AlterField(
            model_name="recurringschedule",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="recurringschedule",
            name="next_run_date",
            field=models.DateField(db_index=True, verbose_name="Next run date"),
        ),
        migrations.AlterField(
            model_name="recurringschedule",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("paused", "Paused"), ("cancelled", "Cancelled")],
                db_index=True,
                default="active",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="recurringschedule",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Timestamp when this record was last modified.",
                verbose_name="Updated at",
            ),
        ),
    ]
