# Generated by Django 5.1.15 on 2026-07-07 08:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_phase2_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("slug", models.SlugField(max_length=120, unique=True, verbose_name="Slug")),
                (
                    "logo",
                    models.ImageField(blank=True, upload_to="brands/logos/", verbose_name="Logo"),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Featured brands appear on the homepage.",
                        verbose_name="Is featured",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
                "indexes": [models.Index(fields=["is_featured"], name="cat_brand_is_featured_idx")],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the category.",
                        max_length=120,
                        verbose_name="Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly category identifier.",
                        max_length=120,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower values appear first in navigation.",
                        verbose_name="Display order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="When False, category is hidden from the storefront.",
                        verbose_name="Is active",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent node in the category tree; null for top-level.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="catalog.category",
                        verbose_name="Parent category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Occasion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                ("slug", models.SlugField(max_length=120, unique=True, verbose_name="Slug")),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        help_text="Small icon shown on occasion chips.",
                        upload_to="occasions/icons/",
                        verbose_name="Icon",
                    ),
                ),
                (
                    "is_seasonal",
                    models.BooleanField(
                        default=False,
                        help_text="When True, occasion is only promoted within active date range.",
                        verbose_name="Is seasonal",
                    ),
                ),
                (
                    "active_from",
                    models.DateField(
                        blank=True,
                        help_text="First day this seasonal occasion is promoted.",
                        null=True,
                        verbose_name="Active from",
                    ),
                ),
                (
                    "active_to",
                    models.DateField(
                        blank=True,
                        help_text="Last day this seasonal occasion is promoted.",
                        null=True,
                        verbose_name="Active to",
                    ),
                ),
            ],
            options={
                "verbose_name": "Occasion",
                "verbose_name_plural": "Occasions",
                "indexes": [models.Index(fields=["slug"], name="cat_occasion_slug_idx")],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                (
                    "sku",
                    models.CharField(
                        db_index=True,
                        help_text="Stock keeping unit identifier.",
                        max_length=64,
                        unique=True,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Default price before variant deltas.",
                        max_digits=12,
                        verbose_name="Base price",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Primary color for PLP color-filter chips.",
                        max_length=50,
                        verbose_name="Color",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
                ),
                (
                    "is_same_day_eligible",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Same-day eligible"
                    ),
                ),
                (
                    "is_bestseller",
                    models.BooleanField(db_index=True, default=False, verbose_name="Is bestseller"),
                ),
                (
                    "is_new_arrival",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Is new arrival"
                    ),
                ),
                (
                    "supports_gift_customization",
                    models.BooleanField(
                        default=False,
                        help_text="When True, gifting app attaches customization options via ContentType.",
                        verbose_name="Supports gift customization",
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Stock quantity"),
                ),
                (
                    "low_stock_threshold",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Triggers low-stock alerts when stock falls at or below this value.",
                        verbose_name="Low stock threshold",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.brand",
                        verbose_name="Brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "primary_occasion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_products",
                        to="catalog.occasion",
                        verbose_name="Primary occasion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/images/", verbose_name="Image")),
                ("alt_text", models.CharField(blank=True, max_length=255, verbose_name="Alt text")),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="Display order"),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Primary image shown on PLP cards and homepage rails.",
                        verbose_name="Is primary",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product image",
                "verbose_name_plural": "Product images",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[("related", "Related"), ("fbt", "Frequently Bought Together")],
                        max_length=20,
                        verbose_name="Relation type",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations",
                        to="catalog.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "related_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_from",
                        to="catalog.product",
                        verbose_name="Related product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product relation",
                "verbose_name_plural": "Product relations",
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "variant_type",
                    models.CharField(
                        choices=[("size", "Size"), ("packaging", "Packaging")],
                        max_length=20,
                        verbose_name="Variant type",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "price_delta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Amount added to the product base price.",
                        max_digits=12,
                        verbose_name="Price delta",
                    ),
                ),
                (
                    "sku_suffix",
                    models.CharField(
                        help_text="Appended to the parent product SKU.",
                        max_length=32,
                        verbose_name="SKU suffix",
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Stock quantity"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product variant",
                "verbose_name_plural": "Product variants",
            },
        ),
        migrations.CreateModel(
            name="ProductVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("video_url", models.URLField(verbose_name="Video URL")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, upload_to="products/video_thumbs/", verbose_name="Thumbnail"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="catalog.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product video",
                "verbose_name_plural": "Product videos",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("body", models.TextField(verbose_name="Body")),
                (
                    "is_verified_purchase",
                    models.BooleanField(default=False, verbose_name="Verified purchase"),
                ),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="Moderation status",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="accounts.customerprofile",
                        verbose_name="Customer",
                    ),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Moderated by",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
            },
        ),
        migrations.CreateModel(
            name="ReviewPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("image", models.ImageField(upload_to="reviews/photos/", verbose_name="Image")),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="catalog.review",
                        verbose_name="Review",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review photo",
                "verbose_name_plural": "Review photos",
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["is_active"], name="cat_category_is_active_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "category_id"], name="cat_prod_active_category_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "is_bestseller"], name="cat_prod_active_bestseller_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "is_new_arrival"], name="cat_prod_active_new_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "is_same_day_eligible"], name="cat_prod_same_day_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product", "is_primary"], name="cat_img_product_primary_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productrelation",
            unique_together={("product", "related_product", "relation_type")},
        ),
        migrations.AlterUniqueTogether(
            name="productvariant",
            unique_together={("product", "variant_type", "name")},
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product", "moderation_status"], name="cat_review_product_mod_idx"
            ),
        ),
    ]
