# Generated by Django 5.1.15 on 2026-07-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_phase3_product_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="meta_description",
            field=models.CharField(blank=True, max_length=160, verbose_name="Meta description"),
        ),
        migrations.AddField(
            model_name="category",
            name="meta_title",
            field=models.CharField(blank=True, max_length=70, verbose_name="Meta title"),
        ),
        migrations.AddField(
            model_name="category",
            name="og_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="seo/categories/", verbose_name="Open Graph image"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_description",
            field=models.CharField(blank=True, max_length=160, verbose_name="Meta description"),
        ),
        migrations.AddField(
            model_name="product",
            name="meta_title",
            field=models.CharField(blank=True, max_length=70, verbose_name="Meta title"),
        ),
        migrations.AddField(
            model_name="product",
            name="og_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="seo/products/", verbose_name="Open Graph image"
            ),
        ),
    ]
