# Generated by Django 5.1.15 on 2026-07-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_phase10_performance_seo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly recipient identifier.",
                        max_length=120,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        help_text="Small icon shown on recipient chips.",
                        upload_to="recipients/icons/",
                        verbose_name="Icon",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower values appear first.",
                        verbose_name="Display order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="Is active"),
                ),
            ],
            options={
                "verbose_name": "Recipient",
                "verbose_name_plural": "Recipients",
                "ordering": ["display_order", "name"],
                "indexes": [models.Index(fields=["is_active"], name="cat_recipient_active_idx")],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                help_text="Recipient personas this product is suitable for.",
                related_name="products",
                to="catalog.recipient",
                verbose_name="Recipients",
            ),
        ),
    ]
