# Generated by Django 5.1.15 on 2026-07-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_recipient_product_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_rental',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Rental Eligible'),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='MRP'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Purchase Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='rental_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Rental Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_rental_storefront',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Show Rental in Storefront'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Wholesale Rate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default price before variant deltas.', max_digits=12, verbose_name='Base price'),
        ),
    ]
