# Generated by Django 5.1.15 on 2026-07-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_is_rental_product_mrp_product_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Default price before variant deltas.', max_digits=12, verbose_name='Base price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='MRP'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Purchase Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_rate',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Wholesale Rate'),
        ),
    ]
