# Generated by Django 5.1.15 on 2026-07-17 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_base_price_alter_product_mrp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='primary_occasion',
        ),
        migrations.RemoveField(
            model_name='product',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supports_gift_customization',
        ),
        migrations.DeleteModel(
            name='Occasion',
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
    ]
