# Generated by Django 5.1.15 on 2026-07-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_product_primary_occasion_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='cat_prod_same_day_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_same_day_eligible',
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is featured'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'is_featured'], name='cat_prod_featured_idx'),
        ),
    ]
