# Generated by Django 5.1.15 on 2026-07-20 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_product_cat_prod_same_day_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was first created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated at')),
                ('title', models.CharField(help_text='e.g., User Manual, Installation Guide, Warranty Details', max_length=150, verbose_name='Document Title')),
                ('document_file', models.FileField(help_text='PDF format manuals or brochures.', upload_to='products/documents/', verbose_name='Document File')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower values appear first.', verbose_name='Display order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Document',
                'verbose_name_plural': 'Product Documents',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was first created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated at')),
                ('name', models.CharField(help_text='e.g., Weight, Dimensions, Battery Life, Voltage', max_length=120, verbose_name='Specification Name')),
                ('value', models.CharField(help_text='e.g., 2.5 kg, 12V, Lithium-Ion', max_length=255, verbose_name='Specification Value')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower values appear first.', verbose_name='Display order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Specification',
                'verbose_name_plural': 'Product Specifications',
                'ordering': ['display_order', 'name'],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
