# Generated by Django 5.1.15 on 2026-07-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productdocument_productspecification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wholesale_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, verbose_name='Wholesale Rate'),
        ),
    ]
