# Generated by Django 5.1.15 on 2026-07-21 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_wholesale_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWholesaleTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was first created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated at')),
                ('min_quantity', models.PositiveIntegerField(verbose_name='Min Quantity')),
                ('max_quantity', models.PositiveIntegerField(verbose_name='Max Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Wholesale Price (Per Unit)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_tiers', to='catalog.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Wholesale Tier',
                'verbose_name_plural': 'Wholesale Tiers',
                'ordering': ['min_quantity'],
                'unique_together': {('product', 'min_quantity', 'max_quantity')},
            },
        ),
    ]
