# Generated by Django 5.1.15 on 2026-08-04 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_remove_wholesale_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Default packed height in centimeters.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Height (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Default packed length in centimeters.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Length (cm)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=0.5, help_text='Default packed weight in kilograms, used for courier booking.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight (kg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Default packed width (breadth) in centimeters.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Width (cm)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank to use the product's default height.", max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Height override (cm)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank to use the product's default length.", max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Length override (cm)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Leave blank to use the product's default weight.", max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight override (kg)'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank to use the product's default width.", max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Width override (cm)'),
        ),
    ]
