# Generated by Django 5.1.15 on 2026-08-04 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_height_cm_product_length_cm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Height in centimeters.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Height (cm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length_cm',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Length in centimeters.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Length (cm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=0.5, help_text='Weight in kilograms, used for courier booking.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Width (breadth) in centimeters.', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Width (cm)'),
        ),
    ]
