# Generated by Django 5.1.15 on 2026-09-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_productimage_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Optional — your cost basis, used for margin reporting only. Leave blank if you don't track it. Each variant may carry its own purchase price instead.", max_digits=12, null=True, verbose_name='Purchase Price'),
        ),
    ]
