# Generated by Django 5.1.15 on 2026-09-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_purchase_price_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional', max_digits=12, null=True, verbose_name='Purchase Price'),
        ),
    ]
