# Generated by Django 5.1.15 on 2026-09-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_product_brand_protect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Stock keeping unit identifier. Required for a simple product; optional when the product has variants, since each variant carries its own SKU suffix instead.', max_length=64, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
