# Generated by Django 5.1.15 on 2026-09-15 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0021_product_sku_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Video slide (mp4/webm). Takes priority over the photo in the gallery.",
                upload_to="products/images/videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(["mp4", "webm", "ogg", "mov"])
                ],
                verbose_name="Video",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Photo slide. Also used as the video's thumbnail when a video is uploaded below.",
                upload_to="products/images/",
                verbose_name="Image",
            ),
        ),
    ]
