# Generated by Django 5.1.15 on 2026-09-15 15:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0022_productimage_video_alter_productimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gst_rate_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("18.00"),
                help_text="GST % already included in this product's prices. Common slabs: 0/5/12/18/28.",
                max_digits=5,
                verbose_name="GST Rate (%)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="hsn_code",
            field=models.CharField(
                blank=True,
                help_text="4-8 digit HSN (goods) or SAC (services) code shown on GST invoices.",
                max_length=8,
                verbose_name="HSN/SAC Code",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="gst_rate_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Leave blank to inherit the product's GST rate.",
                max_digits=5,
                null=True,
                verbose_name="GST Rate override (%)",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="hsn_code",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to inherit the product's HSN/SAC code.",
                max_length=8,
                null=True,
                verbose_name="HSN/SAC override",
            ),
        ),
    ]
