# Generated by Django 5.1.15 on 2026-09-16 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0023_product_gst_rate_percent_product_hsn_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Combo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("slug", models.SlugField(max_length=220, unique=True, verbose_name="Slug")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="combos/", verbose_name="Image"
                    ),
                ),
                (
                    "combo_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Fixed total price charged for one unit of this combo, across all its component products.",
                        max_digits=12,
                        verbose_name="Combo price",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="When False, hidden from the storefront and cannot be added to cart.",
                        verbose_name="Is active",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower values appear first in combo listings.",
                        verbose_name="Display order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combo",
                "verbose_name_plural": "Combos",
                "ordering": ["display_order", "name"],
                "indexes": [models.Index(fields=["is_active"], name="cat_combo_is_active_idx")],
            },
        ),
        migrations.CreateModel(
            name="ComboItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="Quantity")),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.combo",
                        verbose_name="Combo",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="combo_items",
                        to="catalog.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank when the product has no variants, or to bundle its base form.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="combo_items",
                        to="catalog.productvariant",
                        verbose_name="Variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combo item",
                "verbose_name_plural": "Combo items",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("combo", "product", "variant"),
                        name="combo_item_unique_product_variant",
                    )
                ],
            },
        ),
    ]
