# Generated by Django 5.1.15 on 2026-09-16 09:21

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0024_combo_comboitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combo",
            name="combo_price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Fixed total price charged for one unit of this combo, across all its component products.",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Combo price",
            ),
        ),
    ]
