# Generated by Django 5.1.15 on 2026-09-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0025_alter_combo_combo_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combo",
            name="description",
            field=models.TextField(blank=True, max_length=5000, verbose_name="Description"),
        ),
    ]
