# Generated by Django 5.1.15 on 2026-09-18 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0026_alter_combo_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComboDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., How it's used, What's included, Care instructions",
                        max_length=150,
                        verbose_name="Title",
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        help_text="Image, video, or PDF file.",
                        upload_to="combos/documents/",
                        verbose_name="Document File",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, help_text="Lower values appear first.", verbose_name="Display order"
                    ),
                ),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="catalog.combo",
                        verbose_name="Combo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combo Document",
                "verbose_name_plural": "Combo Documents",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.AlterField(
            model_name="productdocument",
            name="document_file",
            field=models.FileField(
                help_text="Image, video, or PDF file.",
                upload_to="products/documents/",
                verbose_name="Document File",
            ),
        ),
    ]
