# Generated by Django 5.1.15 on 2026-09-18 00:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0027_combodocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComboImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Photo slide. Also used as the video's thumbnail when a video is uploaded below.",
                        upload_to="combos/images/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Video slide (mp4/webm). Takes priority over the photo in the gallery.",
                        upload_to="combos/images/videos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["mp4", "webm", "ogg", "mov"])
                        ],
                        verbose_name="Video",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(blank=True, max_length=255, verbose_name="Alt text"),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(default=0, verbose_name="Display order"),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Primary image shown on combo cards and rails.",
                        verbose_name="Is primary",
                    ),
                ),
                (
                    "combo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.combo",
                        verbose_name="Combo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combo image",
                "verbose_name_plural": "Combo images",
                "ordering": ["-is_primary", "display_order"],
            },
        ),
        migrations.AddIndex(
            model_name="comboimage",
            index=models.Index(fields=["combo", "is_primary"], name="cat_cimg_combo_primary_idx"),
        ),
    ]
