# Generated by Django 5.1.15 on 2026-09-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0028_comboimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Full product write-up shown on the product detail page. Not the same as Meta description below, which is the short SEO snippet search engines show.",
                max_length=5000,
                verbose_name="Description",
            ),
        ),
    ]
