# Generated by Django 5.1.15 on 2026-09-22 08:30

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0029_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combodocument",
            name="document_file",
            field=models.FileField(
                help_text="Image, video, or PDF file. Max 15 MB.",
                upload_to="combos/documents/",
                validators=[catalog.validators.MaxFileSizeValidator(15)],
                verbose_name="Document File",
            ),
        ),
        migrations.AlterField(
            model_name="combodocument",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Optional — e.g., How it's used, What's included, Care instructions. Falls back to the file name when left blank.",
                max_length=150,
                verbose_name="Title",
            ),
        ),
        migrations.AlterField(
            model_name="productdocument",
            name="document_file",
            field=models.FileField(
                help_text="Image, video, or PDF file. Max 15 MB.",
                upload_to="products/documents/",
                validators=[catalog.validators.MaxFileSizeValidator(15)],
                verbose_name="Document File",
            ),
        ),
        migrations.AlterField(
            model_name="productdocument",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Optional — e.g., User Manual, Installation Guide, Warranty Details. Falls back to the file name when left blank.",
                max_length=150,
                verbose_name="Document Title",
            ),
        ),
    ]
