# Generated by Django 5.1.15 on 2026-09-25 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_address_company_name_address_gstin_and_more"),
        ("catalog", "0030_alter_combodocument_document_file_and_more"),
        ("orders", "0008_ordernumbersequence"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="Delivered order this review was submitted against, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                condition=models.Q(("order__isnull", False)),
                fields=("order", "product"),
                name="cat_review_unique_order_product",
            ),
        ),
    ]
