# Generated by Django 5.1.15 on 2026-07-07 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_phase2_initial"),
        ("catalog", "0001_phase3_product_catalog"),
        ("core", "0003_seed_default_currency"),
        ("delivery", "0002_phase5_gift_customization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Django session key for guest carts.",
                        max_length=40,
                        null=True,
                        verbose_name="Session key",
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(blank=True, max_length=40, verbose_name="Coupon code"),
                ),
                (
                    "coupon_discount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Coupon discount"
                    ),
                ),
                (
                    "delivery_charge",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="Delivery charge"
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="carts",
                        to="core.currency",
                        verbose_name="Currency",
                    ),
                ),
                (
                    "customer_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to="accounts.customerprofile",
                        verbose_name="Customer profile",
                    ),
                ),
                (
                    "destination_city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carts",
                        to="delivery.city",
                        verbose_name="Destination city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart",
                "verbose_name_plural": "Carts",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="Quantity")),
                (
                    "unit_price_at_add",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Snapshotted price when the item entered the cart.",
                        max_digits=12,
                        verbose_name="Unit price at add",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cart.cart",
                        verbose_name="Cart",
                    ),
                ),

                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="catalog.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cart_items",
                        to="catalog.productvariant",
                        verbose_name="Variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cart item",
                "verbose_name_plural": "Cart items",
            },
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["session_key"], name="cart_session_key_idx"),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["customer_profile"], name="cart_customer_idx"),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("customer_profile__isnull", False), ("session_key__isnull", True)),
                    models.Q(("customer_profile__isnull", True), ("session_key__isnull", False)),
                    _connector="OR",
                ),
                name="cart_owner_xor",
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["cart"], name="cart_item_cart_idx"),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product", "variant"), name="cart_item_unique_product_variant"
            ),
        ),
    ]
