# Generated by Django 5.1.15 on 2026-07-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_phase9_admin_cms_marketing_reports"),
        ("cart", "0001_phase6_cart_checkout_payments"),
        ("core", "0004_phase9_admin_cms_marketing_reports"),
        ("delivery", "0004_phase9_admin_cms_marketing_reports"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(
                fields=["updated_at", "customer_profile"], name="cart_abandoned_scan_idx"
            ),
        ),
    ]
