# Generated by Django 5.2.17 on 2026-08-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_address_city_name_address_state_name_and_more'),
        ('cart', '0002_phase10_performance_seo'),
        ('core', '0015_switch_default_currency_to_inr'),
        ('delivery', '0006_remove_deliveryslotbooking_slot_delete_deliveryslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_buy_now',
            field=models.BooleanField(db_index=True, default=False, help_text="Isolated single-item cart created by the PDP 'Buy Now' action. Never returned by the persistent-cart lookups, never merged on login, and always independent of the customer's real cart.", verbose_name='Is buy-now cart'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_buy_now', 'customer_profile'], name='cart_buy_now_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['is_buy_now', 'session_key'], name='cart_buy_now_session_idx'),
        ),
    ]
