# Generated by Django 5.1.15 on 2026-09-16 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_buy_now_cart"),
        ("catalog", "0024_combo_comboitem"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="cart_item_unique_product_variant",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="combo",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this line was added as part of a product combo — its price is the combo's prorated share rather than the product's live catalog price.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="catalog.combo",
                verbose_name="Source combo",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="combo_name_snapshot",
            field=models.CharField(
                blank=True,
                help_text="Combo name at the time this line was added — survives the combo being edited or deleted.",
                max_length=150,
                verbose_name="Combo name snapshot",
            ),
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["combo"], name="cart_item_combo_idx"),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product", "variant", "combo"),
                name="cart_item_unique_product_variant_combo",
            ),
        ),
    ]
