# Generated by Django 5.1.15 on 2026-08-04 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_remove_order_delivery_slot_booking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when this record was first created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Timestamp when this record was last modified.', verbose_name='Updated at')),
                ('shiprocket_order_id', models.CharField(blank=True, max_length=100, verbose_name='Shiprocket order ID')),
                ('shiprocket_shipment_id', models.CharField(blank=True, max_length=100, verbose_name='Shiprocket shipment ID')),
                ('awb_code', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='AWB code')),
                ('courier_name', models.CharField(blank=True, max_length=100, verbose_name='Courier name')),
                ('label_url', models.URLField(blank=True, verbose_name='Label URL')),
                ('current_status', models.CharField(choices=[('pending_creation', 'Pending creation'), ('created', 'Created'), ('awb_assigned', 'AWB assigned'), ('pickup_scheduled', 'Pickup scheduled'), ('label_generated', 'Label generated'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('error', 'Error')], db_index=True, default='pending_creation', max_length=20, verbose_name='Current status')),
                ('tracking_data', models.JSONField(blank=True, default=dict, verbose_name='Tracking data')),
                ('is_cancelled', models.BooleanField(db_index=True, default=False, verbose_name='Is cancelled')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled at')),
                ('error_log', models.TextField(blank=True, verbose_name='Error log')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='orders.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'indexes': [models.Index(fields=['awb_code'], name='shp_shipment_awb_idx'), models.Index(fields=['shiprocket_order_id'], name='shp_shipment_sr_order_idx'), models.Index(fields=['shiprocket_shipment_id'], name='shp_shipment_sr_ship_idx'), models.Index(fields=['is_cancelled'], name='shp_shipment_cancelled_idx')],
            },
        ),
    ]
