# Generated by Django 5.1.15 on 2026-07-07 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_phase2_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable unique order reference.",
                        max_length=32,
                        unique=True,
                        verbose_name="Order number",
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current lifecycle state of the order.",
                        max_length=20,
                        verbose_name="Order status",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Order total in the customer's checkout currency.",
                        max_digits=12,
                        verbose_name="Total amount",
                    ),
                ),
                (
                    "customer_profile",
                    models.ForeignKey(
                        help_text="Owner of this order.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="accounts.customerprofile",
                        verbose_name="Customer profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["customer_profile", "-created_at"], name="ord_customer_created_idx"
                    ),
                    models.Index(fields=["order_status"], name="orders_order_status_idx"),
                ],
            },
        ),
    ]
