# Generated by Django 5.1.15 on 2026-07-07 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_phase2_initial"),
        ("cart", "0001_phase6_cart_checkout_payments"),
        ("catalog", "0001_phase3_product_catalog"),
        ("core", "0003_seed_default_currency"),
        ("orders", "0001_phase2_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Quantity")),
                (
                    "unit_price_at_purchase",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Unit price at purchase"
                    ),
                ),
            ],
            options={
                "verbose_name": "Order line item",
                "verbose_name_plural": "Order line items",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="cart.cart",
                verbose_name="Source cart",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="core.currency",
                verbose_name="Currency",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_address_snapshot",
            field=models.JSONField(default=dict, verbose_name="Delivery address snapshot"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Client-supplied key preventing duplicate order creation.",
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Idempotency key",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_details",
            field=models.JSONField(default=dict, verbose_name="Invoice details"),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="Order status",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["idempotency_key"], name="orders_idempotency_key_idx"),
        ),

        migrations.AddField(
            model_name="orderlineitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="line_items",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
        migrations.AddField(
            model_name="orderlineitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_line_items",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="orderlineitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_line_items",
                to="catalog.productvariant",
                verbose_name="Variant",
            ),
        ),
        migrations.AddIndex(
            model_name="orderlineitem",
            index=models.Index(fields=["order"], name="order_line_item_order_idx"),
        ),
    ]
