# Generated by Django 5.1.15 on 2026-07-07 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_phase9_admin_cms_marketing_reports"),
        ("catalog", "0001_phase3_product_catalog"),
        ("delivery", "0004_phase9_admin_cms_marketing_reports"),
        ("orders", "0003_phase7_delivery_order_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "Order item", "verbose_name_plural": "Order items"},
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of this order; null for guest checkout.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="accounts.customerprofile",
                verbose_name="Customer profile",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_slot_booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="delivery.deliveryslotbooking",
                verbose_name="Delivery slot booking",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("received", "Received"),
                    ("preparing", "Preparing"),
                    ("packaging", "Packaging"),
                    ("ready", "Ready"),
                    ("out_for_delivery", "Out for delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("refunded", "Refunded"),
                ],
                db_index=True,
                default="received",
                max_length=20,
                verbose_name="Order status",
            ),
        ),

        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="catalog.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Unit price"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="catalog.productvariant",
                verbose_name="Variant",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="changed_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Changed at"),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="changed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_status_changes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Changed by",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when this record was first created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="from_status",
            field=models.CharField(max_length=20, verbose_name="From status"),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="note",
            field=models.TextField(blank=True, verbose_name="Note"),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="to_status",
            field=models.CharField(max_length=20, verbose_name="To status"),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Timestamp when this record was last modified.",
                verbose_name="Updated at",
            ),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="Timestamp when this record was first created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="delivered_at",
            field=models.DateTimeField(verbose_name="Delivered at"),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proof_of_delivery",
                to="orders.order",
                verbose_name="Order",
            ),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="photo_url",
            field=models.URLField(blank=True, verbose_name="Photo URL"),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="recipient_name",
            field=models.CharField(max_length=120, verbose_name="Recipient name"),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="signature_url",
            field=models.URLField(blank=True, verbose_name="Signature URL"),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="Timestamp when this record was last modified.",
                verbose_name="Updated at",
            ),
        ),
    ]
