# Generated by Django 5.1.15 on 2026-07-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_phase9_admin_cms_marketing_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_slot_booking',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Delivery date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('received', 'Placed'), ('preparing', 'Preparing'), ('packaging', 'Packaging'), ('ready', 'Ready'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='received', max_length=20, verbose_name='Order status'),
        ),
    ]
