# Generated by Django 5.1.15 on 2026-09-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_order_delivery_slot_booking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_interstate",
            field=models.BooleanField(
                default=False,
                help_text="Snapshotted at placement from seller vs delivery state. Not re-derived later.",
                verbose_name="Interstate supply",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="total_taxable_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="gst_rate_percent_snapshot",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="GST Rate (%)"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="hsn_code_snapshot",
            field=models.CharField(blank=True, max_length=8, verbose_name="HSN/SAC Code"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="taxable_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="unit_price x quantity with GST reverse-calculated out.",
                max_digits=12,
            ),
        ),
    ]
