# Generated by Django 5.1.15 on 2026-09-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_is_interstate_order_total_tax_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="combo_name_snapshot",
            field=models.CharField(
                blank=True,
                help_text="Name of the combo this line was purchased as part of, if any.",
                max_length=150,
                verbose_name="Combo name snapshot",
            ),
        ),
    ]
