# Generated by Django 5.1.15 on 2026-09-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_orderitem_combo_name_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderNumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when this record was first created.",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="Timestamp when this record was last modified.",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        help_text="Indian financial year, e.g. 2627 for April 2026 – March 2027. Numbering restarts each year.",
                        max_length=8,
                        unique=True,
                        verbose_name="Series",
                    ),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(default=0, verbose_name="Last number issued"),
                ),
            ],
            options={
                "verbose_name": "Bill number sequence",
                "verbose_name_plural": "Bill number sequences",
            },
        ),
    ]
